#!/bin/bash
if [ -d "./apache-jena-fuseki-3.16.0" ] 
then
	echo "Fuseki-server is all ready download" 
	cd apache-jena-fuseki-3.16.0
	./fuseki-server --update --mem /adams
	echo finished 
else
	curl -O http://archive.apache.org/dist/jena/binaries/apache-jena-fuseki-3.16.0.tar.gz
	tar -xvf apache-jena-fuseki-3.16.0.tar.gz
	rm apache-jena-fuseki-3.16.0.tar.gz
	cd apache-jena-fuseki-3.16.0
	./fuseki-server --update --mem /adams
	echo finished 
fi
